name:                vary
version:             0.1.0.0
github:              "qqwy/haskell-vary"
license:             MIT
author:              "Marten Wijnja (Qqwy)"
maintainer:          "qqwy@gmx.com"
copyright:           "2024 Marten Wijnja (Qqwy)"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
synopsis: "Vary: Friendly and fast polymorphic variants (open unions/coproducts/extensible sums)"
description: |         
  Vary: Friendly and fast Variant types for Haskell

  Just like tuples are a version of a user-defined product type (only without the field names), a Variant is a version of a user-defined sum type (but without the field names).

  Variant types are the generalization of `Either`. Especially in the situation where you want to handle multiple errors, Variant types are a great abstraction to use.

  Variant types are sometimes called '_polymorphic_ variants' for disambiguation. They are also commonly known as (open) unions, coproducts or extensible sums.

  Please see the full README below or on GitHub at <https://github.com/qqwy/haskell-vary#readme>

dependencies:
- base >= 4.7 && < 5
- deepseq >= 1.4.0  && < 1.5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  other-modules:
    - Vary.Core

executables:
  vary-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vary

tests:
  vary-test:
    main:                spec.hs
    source-dirs:         test/spec
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vary
  doctests:
    main: doctests.hs
    source-dirs: test/doctest
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vary
    - doctest-parallel
  readme:
    main:        test/README.lhs
    ghc-options:
    - -pgmL markdown-unlit
    - -fdefer-type-errors
    - -Wno-deferred-type-errors
    - -Wno-missing-signatures
    - -Wno-unused-matches
    - -Wno-redundant-constraints
    - -Wno-unused-imports
    build-tools: 
    - markdown-unlit:markdown-unlit
    dependencies:  
    - vary
    - markdown-unlit
    - hspec
    - should-not-typecheck
