on: [push]
name: Build with various flags
jobs:
  flags_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flags: ["--flag=vary:-aeson", "--flag=vary:-hashable", "--flag=vary:-quickcheck"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: |
            ~/.stack
            .stack-work
          key: ${{ runner.os }}-stack-withflags-${{ matrix.flags }}-${{ hashFiles('stack.yaml.lock', 'package.yaml') }}
          restore-keys: |
            ${{ runner.os }}-stack-
      - name: Restore cached dependencies
        uses: actions/cache/restore@v3
        id: cache
        with:
            path: ~/.stack
            key: ${{ runner.os }}-stack-withflags-${{ matrix.flags }}-${{ hashFiles('**/*.cabal') }}
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.6.3' # Exact version of ghc to use
          # cabal-version: 'latest'. Omitted, but defaults to 'latest'
          enable-stack: true
          stack-version: 'latest'
      - run: stack build ${{ matrix.flags }}

